# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Budovatel
email: arnost@budovatel.cz
description: >- # this means to ignore newlines until "baseurl:"
  Vítejte v začínajícím skladišti budovatelských písní, básní a odborných statí, které vzalo počátek díky klubu Agitprop serveru Průvodce. Nadále by se zde měly zjevovat budovatelské a jim podobné písně v pořadí, jak budou znovunalézány a přepisovány. Zvuková podoba písní bude zpočátku reprezentována v notách, midi, posléze i ve formátu mp3.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: budovatel
github_username:  arnost

# Build settings
markdown: kramdown
theme: minima
plugins:


collections:
    pisne:
      output: true
    poezie:
      output: true
    state:
      output: true
    obrazky:
      output: true

defaults:
  - scope:
      path: ""
      type: "obrazky"
    values:
      layout: "obrazek"
      permalink: /obrazky.phtml/:title
  - scope:
      path: ""
      type: "pisne"
    values:
      layout: "pisen"
      permalink: /pisen.phtml/:title
  - scope:
      path: ""
      type: "poezie"
    values:
      layout: "poezie"
      permalink: /poezie.phtml/:title
  - scope:
      path: ""
      type: "state"
    values:
      layout: "poezie"
      permalink: /state.phtml/:title
  - scope:
      path: "noty/jpg"
    values:
      image: true
  - scope:
      path: "noty/lylipond"
    values:
      lylipond: true
  - scope:
      path: "noty/midi"
    values:
      midi: true
  - scope:
      path: "noty/mp3"
    values:
      mp3: true
  - scope:
      path: "noty/ps"
    values:
      ps: true
  - scope:
      path: "noty/pdf"
    values:
      pdf: true
  - scope:
      path: "img"
    values:
      obrazek: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
